{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  "num_layers": 12,
  "hidden_size": 768,
  "num_attention_heads": 12,
  "qkv_slot_num": 576,
  "proj_slot_num": 576,
  "ffn_slot_num": 2304,
  "seq_length": 1024,
  "max_position_embeddings": 1024,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": false,
  "norm": "layernorm_nonparam",
  "final_norm": "layernorm",
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "use_bias_in_attn_linear": false,
  # incremental scaling
  "attention_config": [[["flow_chunk"], 12]],
  "qkv_slot_num_new": 832,
  "proj_slot_num_new": 832,
  "ffn_slot_num_new": 3328,
  "load_module_strict": false,
  "old_lr_decay": true,
  "old_lr_decay_scale": 1.0,
  "seed": 2234,


  # "attention_config": [[["flash"], 12]],

  # these should provide some speedup but takes a while to build, set to true if desired
  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,
  "rope_fusion": false,
  "layernorm_fusion": false,

  "init_method": "normal", # "small_init",
  "output_layer_init_method": "normal",
  "init_method_std": 0.0,

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.0001,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.00001,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  "train_micro_batch_size_per_gpu": 32, # 16gpu
  "gradient_accumulation_steps": 2,
  "data_impl": "mmap",
  "num_workers": 6,

  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "train_iters": 143000,
  "lr_decay_iters": 143000,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,
  "checkpoint_factor": 100,
  "extra_save_iters": [0,1,2,4,8,16,32,64,128],
  "eval_interval": 100,
  "eval_iters": 100,

  "log_interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,
  "keep_last_n_checkpoints": 2000,

  "scale_pretrain": "/u/wangh/workspace_ptmp/checkpoints_gptneox/flownet_v2/L12_dim768_qkv576_proj_576_ffn2304/checkpoints/",
  "save": "/u/wangh/workspace_ptmp/checkpoints_gptneox/continual_training/flownet/L12_dim768_qkv576_proj_576_ffn2304_new832_difflr_seed2234/checkpoints",
  "load": "/u/wangh/workspace_ptmp/checkpoints_gptneox/continual_training/flownet/L12_dim768_qkv576_proj_576_ffn2304_new832_difflr_seed2234/checkpoints",
  "log_dir": "/u/wangh/workspace_ptmp/checkpoints_gptneox/continual_training/flownet/L12_dim768_qkv576_proj_576_ffn2304_new832_difflr_seed2234/logs_1",
  "checkpoint_validation_with_forward_pass": False,
  "adlr_autoresume": True,


  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/u/wangh/workspace/project/NextModel/gpt-neox/pythia/utils/20B_tokenizer.json",

  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,

  "data_path": "/u/wangh/workspace/dataset/language_dataset/pile/pile_0.87_deduped_text_document", # "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  "tensorboard_dir": "tensorboard",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
